name: Create TEST PR

# Run when a PR is merged
#on:
#  pull_request:
#    types: [closed]

# run when a push Occurs to the develop branch
on:
  push:
    branches:
    - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "test"
        pr_title: "Pulling ${{ github.ref }} into TEST"
        pr_body: ":crown: *An automated PR*"  # Full markdown support, requires pr_title to be set
        pr_label: "auto-pr"                   # Comma-separated list (no spaces)
        pr_draft: true                        # Creates pull request as draft
        github_token: ${{ secrets.GITHUB_TOKEN }}